### PR TITLE
Exclude them vulns

### LINKED ISSUE #10: Add ability to exclude vulnerabilities by command line or via file
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Similar to what we did in `nancy`, add the ability to exclude vulnerabilities from failing a build!

https://github.com/sonatype-nexus-community/nancy/pull/30

https://github.com/sonatype-nexus-community/nancy/pull/28

https://github.com/sonatype-nexus-community/nancy/pull/35

https://github.com/sonatype-nexus-community/nancy/pull/29

* **What feature or behavior is this required for?**

This will allow someone to review what vulnerabilities they are affected by, and then exclude the ones they don't find a risk to their project.

* **How could we solve this issue? (Not knowing is okay!)**

I would imagine the best way is to take the functionality we wrote in Nancy, and make it so that Ahab can just leverage it, that way if other projects want to implement this in the future, they can easily do so!

* **Anything else?**

FUN!

cc @bhamail / @DarthHater / @ken-duck

### PR DESCRIPTION
**Pull request by DarthHater**
Add the ability to exclude vulns to ahab

This pull request makes the following changes:
* Drags over functionality from Nancy (`audit.go` and changes to `chase.go`)

It relates to the following issue #s:
* Fixes #10 

cc @bhamail / @DarthHater

### CODE REVIEW

**Comment by MichelKazi** [comment]
This is nice, just tested it and I'm pretty satisfied with the results.
Just a question: would the flag `--exclude` suffice in lieu of `--exclude-vulnerability`?

**Comment by DarthHater** [comment]
@MichelKazi it could, I generally prefer to have a bit more descriptive flags (what is it excluding!?), but if the crowd outvotes me I'll change it!

**Comment by zendern** [comment]
> @MichelKazi it could, I generally prefer to have a bit more descriptive flags (what is it excluding!?), but if the crowd outvotes me I'll change it!

I'd concur with more descriptive.... It also matches nancy. I mean not that it has to but feels like if you use one tool from us it's maybe a good thing to have some consistency. ¯\_(ツ)_/¯ 

From nancy
```
 -exclude-vulnerability value
        Comma separated list of CVEs to exclude
  -exclude-vulnerability-file string
        Path to a file containing newline separated CVEs to be excluded (default "./.nancy-ignore")
```

File: cmd/chase.go [hunk 1]
```diff
@@ -53,10 +78,12 @@ func init() {
 	chaseCmd.PersistentFlags().StringVar(&ossIndexUser, "user", "", "Specify your OSS Index Username")
 	chaseCmd.PersistentFlags().StringVar(&ossIndexToken, "token", "", "Specify your OSS Index API Token")
 	chaseCmd.PersistentFlags().StringVar(&output, "output", "text", "Specify the output type you want (json, text, csv)")
+	chaseCmd.Flags().VarP(&cveList, "exclude-vulnerability", "e", "Comma separated list of CVEs to exclude")
 	chaseCmd.PersistentFlags().BoolVar(&loud, "loud", false, "Specify if you want non vulnerable packages included in your output")
 	chaseCmd.PersistentFlags().BoolVar(&quiet, "quiet", false, "Quiet removes the header from being printed")
 	chaseCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Specify if you want no color in your results")
 	chaseCmd.PersistentFlags().CountVarP(&verbose, "", "v", "Set log level, higher is more verbose")
+	chaseCmd.Flags().StringVarP(&excludeVulnerabilityFilePath, "exclude-vulnerability-file", "x", "./.nancy-ignore", "Path to a file containing newline separated CVEs to be excluded")
```
Comment (zendern) [inline cmd/chase.go]: It's probably not nancy-ignore anymore

**Comment by MichelKazi** [comment]
Sick! I like this feature a lot :)

File: cmd/chase.go (hunk 1 above)
Comment (DarthHater) [reply cmd/chase.go]: lol fixed that for you in 6077225
